[build-system]
requires = ["setuptools>=40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dibbs"
version = "0.1.0"
description = "A small library of tools shared across the DIBBS project"
dependencies = ["pydantic==1.10.9", "fastapi>=0.109.1", "uvicorn"]
